Run coverage run -m pytest  -v -s  
  coverage run -m pytest  -v -s  
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.10.21/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.21/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.21/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.21/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.21/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.21/x64/lib
/home/runner/work/_temp/ff97d14f-c3a2-443a-b196-a3db770e21a0.sh: line 1: coverage: command not found
Error: Process completed with exit code 127.
